### ISSUE TITLE
TotalChurn is auto converted to Decimal; change docs

### ISSUE THREAD

**Issue by scottdangelo** [IBM/cloudpakfordata-telco-churn-workshop#123]
DB2 Warehouse does an auto-configure to change the data types. One of the results is that our TotalCharges is converted from String -> decimal.
In our workshop, however, we use Data Refinery to convert TotalCharges from String to Decimal.
WE need to change the instructions to reflect this.
Also, we discovered this using DB2 Warehouse on Cloud, so it might not happen in each case.

**Comment by omidmeh** [comment]
[ ] Let's check if we can force DB2WH not to autodetect
[ ] Check if DV works fine with it
[ ] Check if DR works
[ ] Check if the notebook runs correctly

**Comment by jrtorres** [comment]
tracking in upstream
