### ISSUE TITLE
Change OpenScale GUI workshop to manually configure the monitors

### ISSUE THREAD

**Issue by scottdangelo** [IBM/cloudpakfordata-telco-churn-workshop#125]
The GUI portion of OpenScale uses the Fast Setup of OpenScale, which does everything automatically.
Change this to have the user(s) manually configure the monitors. This will teach more and make for a better workshop experience.

**Comment by scottdangelo** [comment]
Needs screenshots and testing.

**Comment by scottdangelo** [comment]
needs screenshots
needs testing

**Comment by jrtorres** [comment]
tracking in upstream
