### ISSUE TITLE
link to "Exercise 3: Machine Learning with Jupyter" broken

### ISSUE THREAD

**Issue by lee-zhg** [IBM/cloudpakfordata-telco-churn-workshop#130]
In workshop readme, link to "Exercise 3: Machine Learning with Jupyter" is broken.

**Comment by scottdangelo** [comment]
I could not find the broken link. From the `https://app.gitbook.com/@ibm-developer/s/cloudpakfordata-telco-workshop/` page I clicked the table of contents,
under `Telco Workshop` -> `Machine Learning with Jupyter` and it worked to link to `https://app.gitbook.com/@ibm-developer/s/cloudpakfordata-telco-workshop/telco-workshop/machine-learning-in-jupyter-notebook`
Also, we have not referred to `Exercise 3` in a while. Perhaps you are using an old version of the workshop?

**Comment by jrtorres** [comment]
Its broken on the Introduction page. For some reason its linking to the github readme instead of the gitbook page. Will fix in a bit.

**Comment by scottdangelo** [comment]
Filed #163 for broader updates to workshop/README.md and the out-of-date Agenda.
