### ISSUE TITLE
Create single project asset

### ISSUE THREAD

**Issue by jrtorres** [IBM/cloudpakfordata-telco-churn-workshop#131]
Add the assets being imported by participants for various workshop modules into a single project that would be imported as part of the pre-work.

* Jupyter Notebook (for ML model build and OpenScale)
* AutoAI CSV file

**Comment by scottdangelo** [comment]
Also, update the Admin guide and various places in the docs to reflect the new location for the data.

**Comment by jrtorres** [comment]
Fixed in upstream and merged in PR #188
