### ISSUE TITLE
had to modify ConfigureOpenScale.ipynb to save and deploy a model

### ISSUE THREAD

**Issue by lee-zhg** [IBM/cloudpakfordata-telco-churn-workshop#147]
For my testing, I had to change the following code

    published_model_details = wml_client.repository.store_model(model, metadata, training_data=df_data,  pipeline=pipeline)

to

    published_model_details = wml_client.repository.store_model(model=model, pipeline=pipeline, meta_props=metadata, training_data=train_data)

Before I can continue to the next section. Otherwise, the model deployment fails.

**Comment by scottdangelo** [comment]
MIght be because we don't pin the version of `watson-machine-learning-client-V4` and the method signature changed.
@omidmeh will be testing this, so hopefully he can verify, and have a look at the version.

**Comment by scottdangelo** [comment]
I was able to run this without the changes.
@lee-zhg if you can, can you please run this in a notebook cell:
`!pip show watson-machine-learning-client-V4`
my results are:
```Name: watson-machine-learning-client-V4
Version: 1.0.55
Summary: Watson Machine Learning API Client
Home-page: http://wml-api-pyclient-v4.mybluemix.net
Author: IBM
Author-email: svagaral@in.ibm.com, nagiredd@in.ibm.com, kamigupt@in.ibm.com
License: BSD
Location: /cc-home/_global_/python-3.6
Requires: requests, urllib3, pandas, certifi, tqdm, lomond, tabulate, ibm-cos-sdk
Required-by: ```

We should probably pin this, to prevent this issue.

**Comment by jrtorres** [comment]
switched to pinned versions of dependencies
