### ISSUE TITLE
ConfigureOpenScale.ipynb fails

### ISSUE THREAD

**Issue by lee-zhg** [IBM/cloudpakfordata-telco-churn-workshop#148]
I have run the out-of-box auto configuration of OpenScale as user1. When I run ConfigureOpenScale.ipynb as user2, it fails. Is it ok to run the notebook when the data mart already exists?

When running the following codes

subscription = ai_client.data_mart.subscriptions.add(WatsonMachineLearningAsset(        
    model_uid,
    problem_type=ProblemType.BINARY_CLASSIFICATION,
    input_data_type=InputDataType.STRUCTURED,
    label_column='Risk',
    prediction_column='predictedLabel',
    probability_column='probability',
    feature_columns = ["CheckingStatus","LoanDuration","CreditHistory","LoanPurpose","LoanAmount","ExistingSavings","EmploymentDuration","InstallmentPercent","Sex","OthersOnLoan","CurrentResidenceDuration","OwnsProperty","Age","InstallmentPlans","Housing","ExistingCreditsCount","Job","Dependents","Telephone","ForeignWorker"],
    categorical_columns = ["CheckingStatus","CreditHistory","LoanPurpose","ExistingSavings","EmploymentDuration","Sex","OthersOnLoan","OwnsProperty","InstallmentPlans","Housing","Job","Telephone","ForeignWorker"]
))

if subscription is None:
    print('Subscription already exists; get the existing one')
    subscriptions_uids = ai_client.data_mart.subscriptions.get_uids()
    for sub in subscriptions_uids:
        if ai_client.data_mart.subscriptions.get_details(sub)['entity']['asset']['name'] == MODEL_NAME:
            subscription = ai_client.data_mart.subscriptions.get(sub)

It fails with the messages below

subscription = ai_client.data_mart.subscriptions.add(WatsonMachineLearningAsset(        

    model_uid,

    problem_type=ProblemType.BINARY_CLASSIFICATION,

    input_data_type=InputDataType.STRUCTURED,

    label_column='Risk',

    prediction_column='predictedLabel',

    probability_column='probability',

    feature_columns = ["CheckingStatus","LoanDuration","CreditHistory","LoanPurpose","LoanAmount","ExistingSavings","EmploymentDuration","InstallmentPercent","Sex","OthersOnLoan","CurrentResidenceDuration","OwnsProperty","Age","InstallmentPlans","Housing","ExistingCreditsCount","Job","Dependents","Telephone","ForeignWorker"],

    categorical_columns = ["CheckingStatus","CreditHistory","LoanPurpose","ExistingSavings","EmploymentDuration","Sex","OthersOnLoan","OwnsProperty","InstallmentPlans","Housing","Job","Telephone","ForeignWorker"]

))

​

if subscription is None:

    print('Subscription already exists; get the existing one')

    subscriptions_uids = ai_client.data_mart.subscriptions.get_uids()

    for sub in subscriptions_uids:

        if ai_client.data_mart.subscriptions.get_details(sub)['entity']['asset']['name'] == MODEL_NAME:

            subscription = ai_client.data_mart.subscriptions.get(sub)

---------------------------------------------------------------------------
IncorrectValue                            Traceback (most recent call last)
<ipython-input-95-e4b4b28414c2> in <module>
      7     probability_column='probability',
      8     feature_columns = ["CheckingStatus","LoanDuration","CreditHistory","LoanPurpose","LoanAmount","ExistingSavings","EmploymentDuration","InstallmentPercent","Sex","OthersOnLoan","CurrentResidenceDuration","OwnsProperty","Age","InstallmentPlans","Housing","ExistingCreditsCount","Job","Dependents","Telephone","ForeignWorker"],
----> 9     categorical_columns = ["CheckingStatus","CreditHistory","LoanPurpose","ExistingSavings","EmploymentDuration","Sex","OthersOnLoan","OwnsProperty","InstallmentPlans","Housing","Job","Telephone","ForeignWorker"]
     10 ))
     11 

/opt/conda/envs/Python-3.6/lib/python3.6/site-packages/ibm_ai_openscale/subscriptions.py in add(self, asset, deployment_uids, _training_data_schema, _input_data_schema, **kwargs)
    222 
    223             if not keys:
--> 224                 raise IncorrectValue('source_uid', 'The asset with source_uid ' + asset.source_uid + ' cannot be found.')
    225             else:
    226                 client = clients[keys[0]]

IncorrectValue: Incorrect "source_uid" provided.
Reason: The asset with source_uid e416bcd7-22a9-430a-b58a-f4885dc561a1 cannot be found.

**Comment by lee-zhg** [comment]
Ok, got it work. But, I can't use deployment space "openscale-fast-path". Had to use a different name for deployment space.

**Comment by scottdangelo** [comment]
OK, thanks for filing the issue. I've changed this:
`We'll use the GUID for openscale-fast-path as the space_GUID in the method below:`
to this:
`We'll use the GUID for your Deployment space as listed for the default_space in the method below:`
The user will need their own Deployment space. They should not use the existing one from the fast path deplpoyment.
