### ISSUE TITLE
ConfigureOpenScale.ipynb fails

### ISSUE THREAD

**Issue by lee-zhg** [IBM/cloudpakfordata-telco-churn-workshop#149]
The following code fails if there is no data exists in payload logging table

time.sleep(10)
subscription.quality_monitoring.enable(threshold=0.7, min_records=50)

**Comment by lee-zhg** [comment]
As a workaround, I added the commented codes in its previous step,

fields = ["CheckingStatus","LoanDuration","CreditHistory","LoanPurpose","LoanAmount","ExistingSavings","EmploymentDuration","InstallmentPercent","Sex","OthersOnLoan","CurrentResidenceDuration","OwnsProperty","Age","InstallmentPlans","Housing","ExistingCreditsCount","Job","Dependents","Telephone","ForeignWorker"]
values = [
  ["no_checking",13,"credits_paid_to_date","car_new",1343,"100_to_500","1_to_4",2,"female","none",3,"savings_insurance",46,"none","own",2,"skilled",1,"none","yes"],
  ["no_checking",24,"prior_payments_delayed","furniture",4567,"500_to_1000","1_to_4",4,"male","none",4,"savings_insurance",36,"none","free",2,"management_self-employed",1,"none","yes"],
  ["0_to_200",26,"all_credits_paid_back","car_new",863,"less_100","less_1",2,"female","co-applicant",2,"real_estate",38,"none","own",1,"skilled",1,"none","yes"],
  ["0_to_200",14,"no_credits","car_new",2368,"less_100","1_to_4",3,"female","none",3,"real_estate",29,"none","own",1,"skilled",1,"none","yes"],
  ["0_to_200",4,"no_credits","car_new",250,"less_100","unemployed",2,"female","none",3,"real_estate",23,"none","rent",1,"management_self-employed",1,"none","yes"],
  ["no_checking",17,"credits_paid_to_date","car_new",832,"100_to_500","1_to_4",2,"male","none",2,"real_estate",42,"none","own",1,"skilled",1,"none","yes"],
  ["no_checking",33,"outstanding_credit","appliances",5696,"unknown","greater_7",4,"male","co-applicant",4,"unknown",54,"none","free",2,"skilled",1,"yes","yes"],
  ["0_to_200",13,"prior_payments_delayed","retraining",1375,"100_to_500","4_to_7",3,"male","none",3,"real_estate",37,"none","own",2,"management_self-employed",1,"none","yes"]
]

payload_scoring = {"fields": fields,"values": values}
payload = {
    wml_client.deployments.ScoringMetaNames.INPUT_DATA: [payload_scoring]
}
scoring_response = wml_client.deployments.score(deployment_uid, payload)

#records_list = [
#   PayloadRecord(request=payload, 
#                 response=scoring_response,
#                 response_time=1000), 
#   PayloadRecord(request=payload,
#                 response=scoring_response,
#                 response_time=1000)]
#subscription.payload_logging.store(records=records_list)
#subscription.payload_logging.show_table()

print('Single record scoring result:', '\n fields:', scoring_response['predictions'][0]['fields'], '\n values: ', scoring_response['predictions'][0]['values'][0])

**Comment by scottdangelo** [comment]
Thanks for filing the issue. It is not clear to me what code you added. Is it the part in the comments, for the `records_list` and then `payload_logging.store` ?
I've never seen this fail. The payload logging should automatically take place when the cell is run  to do the `wml_client.deployments.score(....)`.

**Comment by jrtorres** [comment]
We've updated these notebooks a bit. Closing this for now but feel free to open again if issue arises again.
