### ISSUE TITLE
Out of date "Customer-Churn-Project.zip" project

### ISSUE THREAD

**Issue by lapertor** [IBM/cloudpakfordata-telco-churn-workshop#214]
When following [the cloudpak course on IBM's website](https://cognitiveclass.ai/courses/end-to-end-data-science-on-cloudpak-for-data), I found myself stuck at the beginning when loading the "Customer-Churn-Project.zip" file as a project on CloudPak, [as shown on the following screen](https://i.imgur.com/bAaW5zx.png). It seems that the file format is no longer supported, and that a new version of the file exported by IBM Cloud's Watson Studio is needed to complete the course.

EDIT: in case the screen disappears someday, the exact error prompted is the following: "You can't import this project because it was exported from a different edition of Watson Studio. You can import only projects that are exported from Watson Studio on IBM Cloud."

**Comment by shaikmoin80** [comment]
same kind of error here..
