### ISSUE TITLE
URL and credentials required to log into Cloud Pak for Data

### ISSUE THREAD

**Issue by thanh-lam** [IBM/cloudpakfordata-telco-churn-workshop#217]
In the Pre-work Section where the project is created, step 2 requires logging into Cloud Pak for Data website. For this workshop to be self-paced without instructor, why the URL for Cloud Pak for Data was not provided?

As for the user login credential, would it work to use the default admin account and password? If not, what will be the alternative for a user account? Can a new account be created as the first step?

This looks like a good workshop but user can't proceed without the above URL and credential.

**Comment by scottdangelo** [comment]
This workshop is not designed to be  self-paced without an instructor.
It requires a cluster that is setup with Cloud Pak for Data, and the `workshop/admin-guide` instructions must be performed.
Sorry, this will not work without those steps.

**Comment by thanh-lam** [comment]
Thanks @scottdangelo for the quick response! The explanation makes sense. I looked and found this git repo when facing the issue in a class on cognitiveclass.ai. It uses the same workshop here. I wonder if you know that class by any chance? Here's the course URL:

https://courses.cognitiveclass.ai/courses/course-v1:IBMDeveloperSkillsNetwork+DS0201EN+2020T4/course/

The problem is that students in the class are facing this exact issue. The class is probably supposed to be monitored by instructors. But, lots of questions posted in the class discussion about this problem and no instructor answering it.

That makes the class bad because students can't start with the lab exercises. I suppose the cluster should have been created for the class. It's a waste if not used.

**Comment by scottdangelo** [comment]
Yes, sorry about that. We have tried to address the issue. I will have my
teammate look at this tomorrow.
Thanks for your patience.

**Comment by thanh-lam** [comment]
Thanks for taking the time to look into the issue! Do you have any new news? Some of the class attendees and myself found the "Try it for free" version of Cloud Pak for Data on IBM Cloud. That seems to be working. I can create a new project but not with the project zip file from this repo. The problem is that the zip file was exported from a back level of Watson Studio which is not compatible with the new CP4D version. Would it be possible if you export the project from the new Watson Studio version that works with CP4D 3.5 (I think)?

**Comment by scottdangelo** [comment]
@thanh-lam In the meantime, a workaround is that you can "Create a Blank Project" instead of creating one from the .zip file. Then, you can upload the data from `https://github.com/IBM/cloudpakfordata-telco-churn-workshop/tree/master/data` and upload the notebooks from `https://github.com/IBM/cloudpakfordata-telco-churn-workshop/tree/master/notebooks`.

**Comment by thanh-lam** [comment]
Thanks again @scottdangelo ! That workaround got me started with the first lab exercise. Glad I found this git repo and your help is much appreciated!
