### ISSUE TITLE
CP4D - menu options changed

### ISSUE THREAD

**Issue by samayamadhavan** [IBM/cloudpakfordata-telco-churn-workshop#67]
Exercise 1 - Step 2
From the menu click on Collections -> Virtualized Data, you'll be brought to the My data section. Here you should see the data that the administrator has assigned to you. Choose the three data sets available and click Assign to start importing it to your project.
options seems to have changed.

![Screen Shot 2019-11-20 at 3 19 41 PM](https://user-images.githubusercontent.com/29441536/69279253-95461c80-0ba9-11ea-9a94-049ea16ca8d1.png)

**Comment by jrtorres** [comment]
fixed in upstream
